server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      httpclient:
        connect-timeout: 30000
        response-timeout: 60s

logging:
  level:
    org.springframework.cloud.gateway: INFO