server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      httpclient:
        connect-timeout: ${CONNECT_TIMEOUT:30000}

        response-timeout: ${RESPONSE_TIMEOUT:60s}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

    fetch-registry: true

    register-with-eureka: true

logging:
  level:
    org.springframework.cloud.gateway: ${LOG_LEVEL:INFO}